[package]
name = "hello_rocket"
version = "0.1.0"
authors = ["Adrian Bernat <adrianbernat105@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.1"
url = "*"
